version: '2.4'

networks:
  lan_access:
    driver: bridge

services:
  celery:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile
    environment:
      - CELERY_CONTAINER_TYPE=worker
    volumes:
      - ./checkers/:/checkers/
    env_file:
      - ./docker_config/postgres/environment.env
    depends_on:
      - redis
      - postgres
    networks:
      - lan_access
      - default
    restart: on-failure

  celerybeat:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile
    environment:
      - CELERY_CONTAINER_TYPE=beat
    volumes:
      - ./docker_volumes/:/volumes/
    env_file:
      - ./docker_config/postgres/environment.env
    depends_on:
      - redis
      - postgres
      - celery
    restart: on-failure

  flower:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile
    environment:
      - CELERY_CONTAINER_TYPE=flower
    env_file:
      - ./docker_config/postgres/environment.env
      - docker_config/celery/flower_environment.env
    depends_on:
      - redis
      - postgres
      - celery
    restart: on-failure


  initializer:
    build:
      context: .
      dockerfile: docker_config/initializer/Dockerfile
    env_file:
      - ./docker_config/postgres/environment.env
    depends_on:
      - redis
      - postgres
    restart: on-failure

  webapi:
    build:
      context: .
      dockerfile: docker_config/webapi/Dockerfile
    env_file:
      - ./docker_config/postgres/environment.env
    depends_on:
      - redis
      - postgres
    restart: on-failure

  react_builder:
    build:
      context: .
      dockerfile: docker_config/react_builder/Dockerfile
    volumes:
      - ./docker_volumes/react_build/:/react_build/
    restart: on-failure

  http_flag_submitter:
    build:
      context: .
      dockerfile: docker_config/http_flag_submitter/Dockerfile
    env_file:
      - ./docker_config/postgres/environment.env
    depends_on:
      - redis
      - postgres
    restart: on-failure

  tcp_flag_submitter:
    build:
      context: .
      dockerfile: docker_config/tcp_flag_submitter/Dockerfile
    env_file:
      - ./docker_config/postgres/environment.env
    depends_on:
      - redis
      - postgres
    ports:
      - 31337:31337
    restart: on-failure

  nginx:
    image: nginx
    volumes:
      - ./docker_config/nginx/conf/:/etc/nginx/conf.d/
      - ./docker_config/nginx/proxy_params:/etc/nginx/proxy_params
      - ./docker_volumes/react_build:/react_build
    depends_on:
      - flower
      - http_flag_submitter
      - webapi
    ports:
      - 8080:80
    restart: on-failure

  redis:
    image: redis
    restart: on-failure

  postgres:
    image: postgres:10.6
    volumes:
      - ./docker_volumes/postgres/data/:/var/lib/postgresql/data/
    env_file:
      - ./docker_config/postgres/environment.env
    restart: on-failure