version: '2.4'

volumes:
  react_build:

services:
  celery:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile.fast
    environment:
      - TEST=1
      - CELERY_CONTAINER_TYPE=worker
    volumes:
      - ./checkers/:/checkers/
    env_file:
      - ./docker_config/postgres/environment.env
    restart: "no"

  celerybeat:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile.fast
    environment:
      - TEST=1
      - CELERY_CONTAINER_TYPE=beat
    env_file:
      - ./docker_config/postgres/environment.env
    restart: "no"

  flower:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile.fast
    environment:
      - TEST=1
      - CELERY_CONTAINER_TYPE=flower
    env_file:
      - ./docker_config/postgres/environment.env
      - docker_config/celery/flower_environment.env
    restart: "no"

  initializer:
    build:
      context: .
      dockerfile: docker_config/initializer/Dockerfile.fast
    env_file:
      - ./docker_config/postgres/environment.env
    environment:
      - TEST=1
    restart: "no"

  webapi:
    build:
      context: .
      dockerfile: docker_config/webapi/Dockerfile.fast
    env_file:
      - ./docker_config/postgres/environment.env
    environment:
      - TEST=1
    tty: true
    restart: "no"

  react_builder:
    build:
      context: .
      dockerfile: docker_config/react_builder/Dockerfile
    volumes:
      - react_build:/react_build/
    environment:
      - TEST=1
    restart: "no"

  socat_flag_submitter:
    build:
      context: .
      dockerfile: docker_config/socat_flag_submitter/Dockerfile.fast
    env_file:
      - ./docker_config/postgres/environment.env
    environment:
      - TEST=1
    ports:
      - 31338:31338
    tty: true
    pids_limit: 100
    restart: "no"

  tcp_flag_submitter:
    build:
      context: .
      dockerfile: docker_config/tcp_flag_submitter/Dockerfile.fast
    env_file:
      - ./docker_config/postgres/environment.env
    environment:
      - TEST=1
    ports:
      - 31337:31337
    tty: true
    restart: "no"

  nginx:
    build:
      context: .
      dockerfile: docker_config/nginx/Dockerfile
    volumes:
      - react_build:/react_build
    ports:
      - 8080:80
      - 80:80
    restart: "no"

  redis:
    image: redis:5.0.5-alpine
    sysctls:
      net.core.somaxconn: 1024
    restart: "no"

  postgres:
    image: postgres:10.8-alpine
    volumes:
      - ./docker_volumes/postgres/data/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./docker_config/postgres/environment.env
    restart: "no"

  test_service:
    build:
      context: .
      dockerfile: docker_config/test_service/Dockerfile
    ports:
      - 10000:10000
    restart: "no"
