version: '2.4'

networks:
  lan_access:
    driver: bridge

services:
  celery:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile
    volumes:
      - ./docker_volumes/:/volumes/
      - ./checkers/:/checkers/
    env_file:
      - ./docker_config/postgres/environment.env
    depends_on:
      - redis
      - postgres
    networks:
      - lan_access
      - default

  initializer:
    build:
      context: .
      dockerfile: docker_config/initializer/Dockerfile
    volumes:
      - ./docker_volumes/:/volumes/
    env_file:
      - ./docker_config/postgres/environment.env
    depends_on:
      - redis
      - postgres

  web_debug:
    build:
      context: .
      dockerfile: docker_config/web_debug/Dockerfile
    volumes:
      - ./docker_volumes/:/volumes/
    env_file:
      - ./docker_config/postgres/environment.env
    depends_on:
      - redis
      - postgres
    ports:
      - 5002:5002

  http_flag_submitter:
    build:
      context: .
      dockerfile: docker_config/http_flag_submitter/Dockerfile
    volumes:
      - ./docker_volumes/:/volumes/
    env_file:
      - ./docker_config/postgres/environment.env
    depends_on:
      - redis
      - postgres
    ports:
      - 5000:5000

  tcp_flag_submitter:
    build:
      context: .
      dockerfile: docker_config/tcp_flag_submitter/Dockerfile
    volumes:
      - ./docker_volumes/:/volumes/
    env_file:
      - ./docker_config/postgres/environment.env
    depends_on:
      - redis
      - postgres
    ports:
      - 31337:31337

  celerybeat:
    build:
      context: .
      dockerfile: docker_config/celerybeat/Dockerfile
    volumes:
      - ./docker_volumes/:/volumes/
    env_file:
      - ./docker_config/postgres/environment.env
    depends_on:
      - redis
      - postgres
      - celery

  flower:
    build:
      context: .
      dockerfile: docker_config/flower/Dockerfile
    env_file:
      - ./docker_config/postgres/environment.env
      - ./docker_config/flower/environment.env
    volumes:
      - ./docker_volumes/:/volumes/
    depends_on:
      - redis
      - postgres
      - celery

  nginx:
    image: nginx
    volumes:
      - ./docker_config/nginx/conf/:/etc/nginx/conf.d/
      - ./docker_config/nginx/proxy_params:/etc/nginx/proxy_params
    depends_on:
      - flower
      - http_flag_submitter
      - web_debug
    ports:
      - 8080:80

  redis:
    image: redis

  postgres:
    image: postgres:10.6
    volumes:
      - ./docker_volumes/postgres/data/:/var/lib/postgresql/data/
    env_file:
      - ./docker_config/postgres/environment.env
