version: '2.4'

volumes:
  react_build:

services:
  celery:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile
    environment:
      - CELERY_CONTAINER_TYPE=worker
    volumes:
      - ./checkers/:/checkers/
    env_file:
      - ./docker_config/postgres/environment.env
    restart: on-failure

  celerybeat:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile
    environment:
      - CELERY_CONTAINER_TYPE=beat
    env_file:
      - ./docker_config/postgres/environment.env
    restart: on-failure

  flower:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile
    environment:
      - CELERY_CONTAINER_TYPE=flower
    env_file:
      - ./docker_config/postgres/environment.env
      - docker_config/celery/flower_environment.env
    restart: on-failure


  initializer:
    build:
      context: .
      dockerfile: docker_config/initializer/Dockerfile
    env_file:
      - ./docker_config/postgres/environment.env
    restart: on-failure

  webapi:
    build:
      context: .
      dockerfile: docker_config/webapi/Dockerfile
    env_file:
      - ./docker_config/postgres/environment.env
    restart: on-failure
    tty: true

  react_builder:
    build:
      context: .
      dockerfile: docker_config/react_builder/Dockerfile
    volumes:
      - react_build:/react_build/
    restart: on-failure

  http_flag_submitter:
    build:
      context: .
      dockerfile: docker_config/http_flag_submitter/Dockerfile
    env_file:
      - ./docker_config/postgres/environment.env
    restart: on-failure

  socat_flag_submitter:
    build:
      context: .
      dockerfile: docker_config/socat_flag_submitter/Dockerfile
    env_file:
      - ./docker_config/postgres/environment.env
    ports:
      - 31338:31338
    restart: on-failure
    tty: true

  tcp_flag_submitter:
    build:
      context: .
      dockerfile: docker_config/tcp_flag_submitter/Dockerfile
    env_file:
      - ./docker_config/postgres/environment.env
    ports:
      - 31337:31337
    restart: on-failure
    tty: true

  nginx:
    build:
      context: .
      dockerfile: docker_config/nginx/Dockerfile
    volumes:
      - react_build:/react_build
    ports:
      - 8080:80
    restart: on-failure

  redis:
    image: redis:5.0.5-alpine
    restart: on-failure
    sysctls:
      net.core.somaxconn: 1024

  postgres:
    image: postgres:10.8-alpine
    volumes:
      - ./docker_volumes/postgres/data/:/var/lib/postgresql/data/
    env_file:
      - ./docker_config/postgres/environment.env
    restart: on-failure